'use client'
import {useEffect,useMemo,useState} from 'react'
import QRCode from 'qrcode'
export default function Admin(){
 const [logged,setLogged]=useState(false),[u,setU]=useState('admin'),[p,setP]=useState(''),[remember,setRemember]=useState(true),[rows,setRows]=useState<any[]>([]),[qr,setQr]=useState(''),[err,setErr]=useState(''),[q,setQ]=useState('')
 const load=async()=>{const r=await fetch('/api/registrations',{cache:'no-store'});if(r.status===401){setLogged(false);return}const j=await r.json();setRows(j.rows||[])}
 useEffect(()=>{if(logged){load();const t=setInterval(load,10000);return()=>clearInterval(t)}},[logged])
 const login=async(e:any)=>{e.preventDefault();const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:u,password:p,remember})});if(r.ok){setLogged(true);setErr('')}else setErr('เข้าสู่ระบบไม่สำเร็จ')}
 const makeQR=async()=>setQr(await QRCode.toDataURL(window.location.origin))
 const filtered=useMemo(()=>rows.filter(r=>Object.values(r).join(' ').toLowerCase().includes(q.toLowerCase())),[rows,q])
 if(!logged)return <main className="admin"><div className="card"><div className="kicker">LLLDO • ADMIN</div><h1 style={{fontFamily:'Prompt',fontSize:36,margin:'8px 0'}}>Seminar Dashboard</h1><p className="hint">เข้าสู่ระบบเพื่อดูและจัดการข้อมูลลงทะเบียนสัมมนา “เขื่อนและเขาในสายหมอก”</p><form onSubmit={login}><div className="field"><label>Username</label><input value={u} onChange={e=>setU(e.target.value)} autoComplete="username"/></div><div className="field" style={{marginTop:14}}><label>Password</label><input type="password" value={p} onChange={e=>setP(e.target.value)} autoComplete="current-password"/></div><label style={{display:'block',margin:'15px 0'}}><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/> จำการเข้าสู่ระบบ 30 วัน</label>{err&&<p className="error">{err}</p>}<button className="btn primary" style={{width:'100%'}}>เข้าสู่ระบบ →</button></form></div></main>
 return <main className="admin"><div className="topbar"><div><div className="kicker">LLLDO • SEMINAR 2569</div><h1 style={{fontFamily:'Prompt',margin:'5px 0'}}>Seminar Dashboard</h1><span className="hint">ข้อมูลรีเฟรชอัตโนมัติทุก 10 วินาที • {filtered.length} รายการ</span></div><button className="btn gold" onClick={makeQR}>สร้าง QR ลงทะเบียน</button></div>
 <div className="stats"><div className="stat">ผู้ลงทะเบียน<br/><b>{rows.length}</b> คน</div><div className="stat">มีผู้ติดตาม<br/><b>{rows.filter(r=>r.follower===true||r.follower==='true').length}</b> ราย</div><div className="stat">เจ / ฮาลาล<br/><b>{rows.filter(r=>['อาหารเจ','อิสลาม (ฮาลาล)'].includes(r.diet)).length}</b> ราย</div><div className="stat">กิจกรรมหลัก<br/><b>{rows.filter(r=>String(r.activity||'').startsWith('เข้าร่วมกิจกรรมและร่วม')).length}</b> ราย</div></div>
 {qr&&<div className="qr"><img src={qr} width={220} alt="QR Code"/><div><b>QR Code สำหรับหน้าลงทะเบียน</b><br/><span className="hint">สแกนด้วยโทรศัพท์เพื่อเปิดแบบฟอร์ม</span></div></div>}
 <div className="tableWrap"><div style={{padding:16,borderBottom:'1px solid #edf0ed'}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ค้นหาชื่อ ฝ่าย โทรศัพท์ อาหาร หรือกิจกรรม..."/></div><table className="table"><thead><tr><th>เวลา</th><th>ชื่อ</th><th>ฝ่าย</th><th>โทรศัพท์</th><th>ผู้ติดตาม</th><th>อาหาร</th><th>แพ้อาหาร</th><th>กิจกรรม</th><th>กิจกรรมย่อย</th></tr></thead><tbody>{filtered.map((r,i)=><tr key={i}><td>{r.timestamp}</td><td><b>{r.name}</b></td><td>{r.department}</td><td>{r.phone}</td><td>{r.follower?`${r.count||0} คน`:'ไม่มี'}</td><td>{r.diet}</td><td>{Array.isArray(r.allergies)?r.allergies.join(', '):r.allergies}</td><td>{r.activity}</td><td>{r.subActivity||r.otherActivity||'-'}</td></tr>)}{filtered.length===0&&<tr><td colSpan={9} style={{textAlign:'center',padding:35,color:'#718079'}}>ไม่พบข้อมูล</td></tr>}</tbody></table></div></main>
}